// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma Migrate should use a direct Postgres connection.
    // Keep DATABASE_URL for pooled runtime traffic and set DIRECT_URL for CLI/migrations.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
